topic_image_height: 
  default: "550px"
  description: "Change the topic list image (thumbnail) section height."
topic_image_fit:
  default: cover
  type: enum
  choices:
    - contain
    - scale-down
    - none
  description: "Select the topic list image (thumbnail) fit. More info: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit"
topic_image_backdrop:
  type: bool
  default: true
  description: "Add backdrop to topic list image (thumbnail)."
topic_image_backdrop_blur: 
  default: "50px"
  description: "Change the topic_image_backdrop blur size. Set a lower value for less blurred backdrop image."
topic_image_backdrop_brightness: 
  default: "0.55"
  description: "Change the topic_image_backdrop brightness size. Set a lower value for less bright backdrop image."

category_badge_style:
  default: bullet
  type: enum
  choices:
    - box
  description: "Select the category badge style."
  
right_sidebar_blocks_enabled:
  type: bool
  default: false
  description: "Enabling this will add Right Sidebar Blocks theme component support and replace the original fkb panel with it."

right_sidebar_below_fkb_panel:
  type: bool
  default: false
  description: "Enabling this will add Right Sidebar Blocks theme component below the FKB Panel."

right_sidebar_blocks_expanded:
  type: bool
  default: false
  description: "In this mode the components appears separately and the last component is sticky."
  
custom_sidebar_enabled:
  type: bool
  default: true
  description: "Custom sidebar content for visitor."
custom_sidebar_image:
  type: upload
  default: ""
  description: "Upload an image to display on the sidebar for visitor."
custom_sidebar_description:
  type: string
  textarea: true
  default: |
           GoNomad is all about discussing privacy and security-related topics;
           however, you can also talk about off-topic things if you'd like!
           With an account, you can make posts & replies, have notifications,
           earn custom badges, bookmark posts, use "likes" to thank others and much more.
           We can all work together to make this community even greater. 
  description: "Custom sidebar description for visitors. (HTML allowed)"
  
fkb_panel_items:
  default: >-
    [{"title":"Summary","link":"/my/summary","icon":"user"},
    {"title":"Settings","link":"/my/preferences/account","icon":"cog"},
    {"title":"Drafts","link":"/my/activity/drafts","icon":"pencil-alt"},
    {"title":"Bookmarks","link":"/my/activity/bookmarks","icon":"bookmark"},
    {"title":"Messages","link":"/my/messages","icon":"envelope"}]
  json_schema: >-
    {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },        
          "link": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
fkb_panel_show_solutions:
  type: bool
  default: true
  description: "Enable if you use Discourse Solved plugin."  
fkb_panel_show_badges:
  type: bool
  default: true
border_radius_avatar: 
  type: enum
  default: 50%
  choices: 
    - 0%
    - 10%
    - 20%
    - 30%
    - 40%
    - 50%
  description: "Avatar shape."
border_radius_em: 
  default: "1em"
  description: "Highly rounded corners. We use it on topic list items, posts and modals."
border_radius_button: 
  default: "2em"
  description: "Rounded corners. We use it on buttons. inputs etc..."
border_radius_input: 
  default: "2em"
  description: "Rounded corners. We use it on inputs etc..." 
border_radius_select_body: 
  default: "0.75em"
  description: "Rounded corners. We use it on select-kit body etc..."
light_bg:
  default: "#f0f2f5"
  description: "Light background color"
dark_bg:
  default: "#18191a"
  description: "Dark background color"
light_header_btn:
  default: "#e1e5eb"
  description: "Light header buttons color"
dark_header_btn:
  default: "#3a3b3e"
  description: "Dark header buttons color"
light_header_btn_hover:
  default: "#d2d8e1"
  description: "Light header buttons hover color"
dark_header_btn_hover:
  default: "rgba(var(--primary-rgb),.1)"
  description: "Dark header buttons hover color"
light_btn:
  default: "#c2c8d1"
  description: "Light buttons color"
dark_btn:
  default: "#383838"
  description: "Dark buttons color"
light_btn_hover:
  default: "#d2d8e1"
  description: "Light buttons hover color"
dark_btn_hover:
  default: "rgba(var(--primary-rgb),.1)"
  description: "Dark buttons hover color"